name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  qodana-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Backend'
        uses: JetBrains/qodana-action@v2024.1
        with:
          args: |
            --source-directory,backend,--config,qodana-backend.yaml
          artifact-name: qodana-backend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_BACKEND }}

  qodana-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan - Frontend'
        uses: JetBrains/qodana-action@v2024.1
        with:
          args: |
            --source-directory,frontend,--config,qodana-frontend.yaml
          artifact-name: qodana-frontend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_FRONTEND }}